# Generated by Django 2.0.1 on 2018-03-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='songs',
            options={'verbose_name_plural': 'Songs'},
        ),
        migrations.AddField(
            model_name='songs',
            name='song_url',
            field=models.CharField(default='https://musicpleer.bz/#!98f3c34ee7b892a91c370cb124229dac', max_length=1000),
        ),
    ]
